### ISSUE TITLE
[Request] Network manager icon theme is missing in Gnome panel (at leaset I think!)

### ISSUE THREAD

**Issue by Bonsitar** [keeferrourke/la-capitaine-icon-theme#354] opened 2018-03-04 19:05 UTC
**It's NOT an application icon, It's an icon in Gnome panel that refers to network manager status when I enable vpn or connect with a eth0 connection!**

### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| MyApplication    | `app-icon` | Application | 			   |

### Desktop file

```
# Paste your desktop file below.
# Do NOT include non-English translation strings.




```

Here is the icon looks like wrong when I enabled VPN in la-captain-icon-theme:
![image](https://user-images.githubusercontent.com/35845718/36949248-edb3168a-1ffa-11e8-8803-3633c1ef7569.png)
_The first icon from left side (beside key)
and there when I didn't open any VPN in la-captain-icon-theme:
![image](https://user-images.githubusercontent.com/35845718/36949279-5f072934-1ffb-11e8-9be1-0b48e8fe1341.png)
and here for another example in Flat Remix icon theme it looks like:
![image](https://user-images.githubusercontent.com/35845718/36949357-49327fd6-1ffc-11e8-94db-e1922a8f0afa.png)
much cool and more related, 
Thanks.

**Comment by linusg** [comment] 2018-03-04 19:12
I think there's no icon missing here or whatsoever, it's just two different icons for a wired and wireless connection. No VPN specific thing. Apparently in La Capitaine the wired connection icon is two arrows connected by a line, in Flat Remix it's an ethernet port.
Both seem common, preferring one is based on personal opinions. What's the point?

**Comment by keeferrourke** [comment] 2018-03-04 21:41
Closing this because there is no issue. When a VPN is enabled in GNOME, a new icon for a VPN appears in the status panel, and the network icon changes to look like a wired connection. This is expected behaviour in GNOME, though perhaps a little odd. File an issue with GNOME Shell maintainers if you don't like this behaviour.

**Closed by keeferrourke** 2018-03-04 21:41 UTC

**Comment by Bonsitar** [comment] 2018-03-05 22:48
Oh, I'm sorry.
I thought that it might an icon missing in icon theme pack.
Thanks anyway.
