### ISSUE TITLE
[Mate] [unconfirmed] battery icons are not themed

### ISSUE THREAD

**Issue by Ufeldraku** [keeferrourke/la-capitaine-icon-theme#9] opened 2016-07-25 23:27 UTC
![](http://i.imgur.com/F3D8jAK.png)

**Comment by keeferrourke** [comment] 2016-07-25 23:32
gonna need the icon names mate ;)

**Comment by Ufeldraku** [comment] 2016-07-25 23:33
Huh? Could you explain.
Anyway, that was a really fast reply.

**Comment by keeferrourke** [comment] 2016-07-25 23:38
@Ufeldraku this icon set has battery and sound icons, but different desktop environments and applets use different names to reference these files. 

If you want me to add support for Mate's battery and sound indicators, I need the names of these files.. or at the very least the name of the application that provides the applet.

See the README for how to submit icon requests.

**Comment by Ufeldraku** [comment] 2016-07-25 23:45
mate-volume-control-applet for the sound applet

**Comment by keeferrourke** [comment] 2016-07-25 23:50
Since I have some time right now I did a little searching and it would seem MATE doesn't use the symbolic icons typical of status indicators like battery and sound. I'll add regular versions of the same icons, but no guarantees that this is a proper fix. I'll let you know when I push the commit and I'll need you to test it out :)

**Comment by Ufeldraku** [comment] 2016-07-25 23:52
COOL
And.. Do you need the applet name of battery, because it's a program, not an applet per se :  mate-power-manager

**Comment by Ufeldraku** [comment] 2016-07-25 23:58
> Push the commit.  
Ahh, I installed this from the AUR...

**Comment by keeferrourke** [comment] 2016-07-26 00:04
Updated status icons in commit [4d6c115](https://github.com/keeferrourke/la-capitaine-icon-theme/commit/4d6c115), let me know if it solves your problem :)

**Comment by keeferrourke** [comment] 2016-07-26 00:06
> Ahh, I installed this from the AUR...

There's an AUR package for my theme? Cool! I'll need to check that out; it probably just pulls from this repo anyway so just update your system with `yaourt -Syu` or whatever AUR helper you're using on your system :)

**Comment by Ufeldraku** [comment] 2016-07-26 00:14
Ok, the sound applet is fine now, however the battery one still uses Adwaita.

**Comment by keeferrourke** [comment] 2016-07-26 00:47
@Ufeldraku Okay so I found a [list of all the files used in Arch's mate-power-manager])https://www.archlinux.org/packages/community/i686/mate-power-manager/files/). Not sure how up to date it is, but because it's Arch I assume its bleeding edge :stuck_out_tongue: 

I've pushed a bunch more battery icon aliases based on what's listed there, so update to commit (46ef470)[https://github.com/keeferrourke/la-capitaine-icon-theme/commit/46ef470] and let me know how it works out.

**Comment by Ufeldraku** [comment] 2016-07-26 00:52
Actually, I'm using antergos, as it has the lastest mate (1.14)

**Comment by keeferrourke** [comment] 2016-07-26 00:57
@Ufeldraku Antergos is based on Arch though. The changes I made should still be relevant.

I installed mate-power-manager which works a little funny under Ubuntu's GNOME3, but it seems to be using the newly updated icons. Can you confirm?

**Comment by Ufeldraku** [comment] 2016-07-26 00:58
No, but antergos ships its own mate packages.

**Comment by Ufeldraku** [comment] 2016-07-26 01:00
Nope, nothing.

**Comment by keeferrourke** [comment] 2016-07-26 01:00
So commit https://github.com/keeferrourke/la-capitaine-icon-theme/commit/46ef470 had no effect for you, even after restarting mate-power-manager?

    killall mate-power-manager
    mate-power-manager &

**Comment by Ufeldraku** [comment] 2016-07-26 01:00
Ya, nothing

**Comment by Ufeldraku** [comment] 2016-07-26 01:01
I force it to change the icons by make the panel larger :p

**Comment by keeferrourke** [comment] 2016-07-26 01:07
Can you refresh your icon cache by selecting Adwaita and then La Capitaine, and then kill all the `mate-power-manager` processes and restart the applet just to confirm?

Use your preferred GUI tools or run this in your terminal:

    gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'
    killall mate-power-manager
    gsettings set org.gnome.desktop.interface icon-theme 'la-capitaine-icon-theme'
    mate-power-manager &

**Comment by Ufeldraku** [comment] 2016-07-26 01:24
Nah nothing, still the same
:(

**Comment by keeferrourke** [comment] 2016-07-26 01:27
@Ufeldraku I'm gonna look into this some more and see what I can do for you, I'm making this high priority.

**Comment by keeferrourke** [comment] 2016-07-26 01:38
Okay so the icons listed in mate's git repository over at https://github.com/mate-desktop/mate-power-manager/tree/master/data/icons/16x16/status match the names in https://github.com/keeferrourke/la-capitaine-icon-theme/tree/master/status/scalable ...

My suggestion would be for you to make sure you've selected La Capitaine as your icon theme, update your system, and then reboot. If the battery applet still isn't themed,  I might have to contact the Antergos distro maintainers.

**Comment by Ufeldraku** [comment] 2016-07-26 02:06
Ok, I'll tell you tomorrow.

**Comment by keeferrourke** [comment] 2016-07-27 00:49
@Ufeldraku Did you try my suggestions?

**Comment by Ufeldraku** [comment] 2016-07-27 16:13
Yeah, none of them worked.
However now I use GNOME; btw, I love you icon theme, keep up with the good work!

**Comment by keeferrourke** [comment] 2016-07-27 17:08
Alright thanks for trying and thanks for the compliments! :+1:  

I'm still going to look into this issue tonight though.

**Comment by Ufeldraku** [comment] 2016-07-27 17:39
Cool

**Comment by Ufeldraku** [comment] 2016-07-28 00:51
Installed xfce4, battery icon is Xfce's default.
Also, Chromium BSU's icon is Chromium's icon, but I think that that is kinda funny

**Comment by keeferrourke** [comment] 2016-07-28 01:08
Regarding the Chromium vs Chromium B.S.U. icons, that really should be in a different bug report... but it is really funny! I'll get it fixed soonish. See issue: https://github.com/keeferrourke/la-capitaine-icon-theme/issues/10

@Ufeldraku XFCE's battery icons *should* be themed. Can you freshly clone this repo and double check?
[XFCE's Github](https://github.com/xfce-mirror/xfce4-power-manager/tree/master/data/icons/scalable) suggests that xfce-power-manager uses the same icons that are already in this project.

I'll look into it when I have some extra time and feel like installing a few test desktop environments.

**Comment by Ufeldraku** [comment] 2016-07-28 14:54
You're cool.
Gonna try my Xfce

**Comment by Ufeldraku** [comment] 2016-07-28 15:04
Nope, It doens't work. 
However, with numix-square it does use the battery icon.

**Comment by keeferrourke** [comment] 2016-07-28 16:32
I haven't tested this, but check out commit https://github.com/keeferrourke/la-capitaine-icon-theme/commit/10e4023 &ndash; I think I fixed the XFCE4 battery icons. I'm not super familiar with the DE, but I think XFCE4 uses [this battery plugin](https://github.com/xfce-mirror/xfce4-battery-plugin) for its panel to display the battery status.

**Comment by getphuture** [comment] 2016-08-05 16:12
You are both right and you probably don't talk about the same thing.
@keeferrourke fixed [the battery plugin](https://github.com/xfce-mirror/xfce4-battery-plugin) (XFCE Applet Battery Monitor), I suppose @keeferrourke added the [power manager plugin](https://github.com/xfce-mirror/xfce4-power-manager) (XFCE Applet Power Manager Plugin)

Xfce, gnome or whatever environment & distro you're using, there should be at least a default icon set with the power manager icons, for example:

>  /usr/share/icons/hicolor/scalable/status/xfpm-*

Icons also includes percent based variants for both laptop and desktop.
It's gonna take you a while... Keep the good work ! 

Cheers

**Comment by keeferrourke** [comment] 2016-08-05 16:26
@getphuture thanks for confirming the XFCE battery icons have been fixed (if I read that correctly) ; I've yet to test XFCE and MATE myself though. I'll try to get to it tomorrow.

**Comment by getphuture** [comment] 2016-08-05 17:42
Yes i tested with a fresh git clone, the battery icon looks good on OpenSuse Leap.
I added the Battery Monitor Item on an xfce panel,  edit the properties and check Display icon and the new icon was showing properly.

As for my previous comment it was just a supposition... I'm using the battery monitor icon (on laptop) so it's good for me. With the power management plugin especially it could become a pain: icon not updating, using non scalable version, wrong setting inherit from theme, ... I'm not asking you to spend an insane amount of time to fix it ;-)

**Comment by Ufeldraku** [comment] 2016-08-08 00:14
Ahh, according to my system, the program's mate-power-manager, it's not an applet, the mate-power-manager draws the icon in the panel.

**Comment by keeferrourke** [comment] 2016-08-08 00:16
@Ufeldraku I just tested with a fresh MATE install, and the system indicators (sounds, wifi, battery) all display properly.

**Comment by keeferrourke** [comment] 2016-08-08 00:17
The [icons that are used by mate-power-manager ](https://github.com/mate-desktop/mate-power-manager/tree/master/data/icons/24x24/status) are all in La Capitaine already. I'm not sure what the problem is.

**Comment by keeferrourke** [comment] 2016-09-05 03:08
Closing because I think this is fixed since #35 addresses the issue of redesigning battery icons in xfce, and local tests seem to indicate that MATE gets themed properly.

**Closed by keeferrourke** 2016-09-05 03:08 UTC
Labels: bug, enhancement
