### ISSUE TITLE
Support for Harcode-tray

### ISSUE THREAD

**Issue by arifcatalyst** [keeferrourke/la-capitaine-icon-theme#260] opened 2017-10-26 07:31 UTC
Please add support for Harcode-tray [https://github.com/bil-elmoussaoui/Hardcode-Tray](url)

**Comment by linusg** [comment] 2017-10-26 07:38
Instead of wasting the maintainer's time, one could look  up the open issues. #125 is exactly the same, opened by the author of above tool.

**Comment by now-im** [comment] 2017-10-26 13:00
It will most peobably come to fruition in version 0.6. Look forward to it!

**Comment by keeferrourke** [comment] 2017-10-28 18:12
Closing as duplicate of #125.

**Closed by keeferrourke** 2017-10-28 18:12 UTC
Labels: duplicate
