### ISSUE TITLE
Bug: gnome-shell crash on Ubuntu 18.04

### ISSUE THREAD

**Issue by austince** [keeferrourke/la-capitaine-icon-theme#375] opened 2018-07-18 03:28 UTC
Hi, first off - thank you for excellent work and support.

Next, I believe this is a widespread problem, and not with a specific application, so I'm not including a .desktop file. I'm not entirely sure how to diagnose it, but I'll do my best.

### Description:

Using the icon theme causes gnome-shell to crash and go back to the login screen when opening some windows. 

Output from `journalctl /usr/bin/gnome-shell`
```
Jul 17 22:21:25 hp org.gnome.Shell.desktop[3216]: **
Jul 17 22:21:25 hp org.gnome.Shell.desktop[3216]: mutter:ERROR:core/window.c:5296:get_default_window_icon: assertion failed: (default_icon)
Jul 17 22:21:25 hp org.gnome.Shell.desktop[3216]: == Stack trace for context 0x562f85c584d0 ==
```

### Steps to Reproduce:
- Install Ubuntu 18.04
- Install `la-capitaine-icon-theme` from ppa
- Install [Jetbrains Toolbox](https://www.jetbrains.com/toolbox/app/) (though was also happening with Tweaks, etc]
- Open Toolbox
- Observe crash 

### My System:

HP Zbook 15

**Graphics Card, using default nouveau drivers:**
 *-display
                description: VGA compatible controller
                product: GK107GLM [Quadro K1100M]
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:01:00.0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
                configuration: driver=nouveau latency=0
                resources: irq:28 memory:cb000000-cbffffff memory:50000000-5fffffff memory:60000000-61ffffff ioport:5000(size=128) memory:cc080000-cc0fffff

Any guidance would be much appreciated, as I love your theme!

**Comment by keeferrourke** [comment] 2018-07-19 01:06
That looks like an assertion failure... Helpfully they have the line number provided, so I'll checkout their source code and look around.

**Comment by austince** [comment] 2018-07-19 12:40
Thank you! This problem doesn't happen when I disable this icon theme or
use other 3rd party icon themes. I don't have too much experience
developing for gnome - sorry I can't be of more help!

**Comment by austince** [comment] 2018-07-19 13:10
Here's the issue on Muxer's repo: https://gitlab.gnome.org/GNOME/mutter/issues/234

**Comment by wowbaggerBR** [comment] 2018-07-29 11:30
I can confirm the exact same issue. Took me a long time to debug it and isolate the cause: it only happes with La Capitaine icons enabled.

The event is the same reported by @austince . In my case, I can reproduce it at will by trying to edit desktop entries with Menu Libre, using the search icons feature.

**Comment by keeferrourke** [comment] 2018-07-30 04:46
Here's the fix: update to the latest version of La Capitaine from the master branch of this repository.

I haven't cut a proper version release since September, and I'd imagine that the third-party repository that you folks are using to install the theme hasn't kept up.

I'm going to cut a new version release ASAP which will hopefully spur PPA maintainers, et. al. to update their packages.

@austince hopefully there will be some more discussion on your issue on the Mutter project. It seems a trivial fix.

**Comment by wowbaggerBR** [comment] 2018-07-30 10:18
Updated and not only the bug is completely solved, but I noticed quite a different set of icons from the PPA version I had installed. Should just had downloaded from here in the first place.

Thank you for your work, I really enjoy it and I'm glad to be able to use it!

**Comment by austince** [comment] 2018-07-30 13:00
Thank you @keeferrourke! Will try it out later and good luck with the Mutter folks

**Comment by austince** [comment] 2018-07-30 17:00
Yup, this fixed it for me! Should I close this issue or leave it up until the ppa is updated?

**Comment by keeferrourke** [comment] 2018-07-30 23:42
I'd probably close this since I don't personally maintain the third-party repositories. I'll try to poke the maintainers though.

@igor-dyatlov would you be able to update the PPA?

**Closed as completed** 2018-07-31 02:23 UTC
Labels: bug, fixed, gnome

**Comment by keeferrourke** [comment] 2018-07-31 04:53
Looks like Fedora COPR repo has been updated :tada:

**Comment by osilkin98** [comment] 2018-08-21 06:58
The issue still persists on `Ubuntu 18.04.1 LTS x86_64` with `DE: GNOME 3.28.2` and `WM: GNOME Shell`, on Gnome on Xorg as well as the default Ubuntu WM as I documented it [here](https://unix.stackexchange.com/questions/463782/gnome-tweak-tool-crashes-forces-logout-when-selecting-fonts)
